Models Created
Web-Team-IITI-Gymkhana/tpc-backend pull request #9
Opened 2023-10-15 13:11 UTC by Manas-wagh

We have created the models corresponding to the tables of the database as per the latest ER diagram.

2023-10-17 11:59 UTC, MihirK1212 commented
@Manas-wagh change the commit name to lower case separated by a hyphen. eg:- 'create-db-models'

2023-10-17 13:12 UTC, MihirK1212 requested changes
I have suggested some high-level changes that need to be addressed.
As there are some pending changes in the ER diagram, I'll review the table relations and specific fields in detail in the next review iteration.

2023-10-17 13:12 UTC, MihirK1212 commented on src/db/models/jaf.ts
> +}
Refer to [this](https://www.npmjs.com/package/sequelize-typescript#model-association) and add HasMany decorators to the table which contains the primary key for the foreign key referenced in some other table.
For eg:- 'Event' model uses jaf id, and the relation between Jaf and Event is one-to-many so use the BelongsTo decorator in Event model, and use the HasMany decorator in the Jaf model.
Do this for all model relations

2023-10-17 13:16 UTC, MihirK1212 commented
@akashg3627 could you please review the folder structure and suggest changes if required

2023-10-17 13:20 UTC, MihirK1212 requested changes

2023-10-17 13:20 UTC, MihirK1212 commented on src/app.module.ts
> +import { databaseModule } from "./db/database.module";
Module name should be 'DatabaseModule'

2023-10-17 14:59 UTC, gjain-7 commented on src/db/models/eligibleRoles.ts
> +  @Column
you're referring to gender right? Its better to avoid unintended possibilities.

2023-10-17 15:15 UTC, gjain-7 commented on src/db/models/event.ts
> +  stage: string;
That is true stages are indeed fixed, but they can have multiple substages or rounds.
So we have 2 options
1.  Leave it as it is.
2. Make it ENUM as you suggested and add a RoundNumber column with integer values.

I think latter would be a better option. Others may want to share their thoughts as well. @akashg3627 ?

2023-10-18 12:43 UTC, MihirK1212 commented on src/db/models/eligibleRoles.ts
> +  @Column
no, I'm referring to branch

2023-10-21 14:32 UTC, Manas-wagh commented on src/db/models/eligibleRoles.ts
> +  category: string;
bhaiyya bohot catagories possible hei.. kya kare?

2023-10-21 14:35 UTC, Manas-wagh commented on src/db/models/company.ts
> +export class companyModel extends Model {
bhiayya sare modules mei yahi kare kya?
table ka naam company hei
isliye models ke naam aaise kare hei... like for company its companyModel.
should we change all?

2023-10-21 14:47 UTC, gjain-7 commented on src/db/models/eligibleRoles.ts
> +  category: string;
GEN, GEN-EWS, SC, ST, PWD, OBC-CL, OBC-NCL

Is there any left?

2023-10-24 12:23 UTC, MihirK1212 requested changes

2023-10-24 12:23 UTC, MihirK1212 commented on src/db/models/event.ts
> +  stae: Stage;
Fix the typo here

2023-10-24 12:23 UTC, MihirK1212 commented on src/db/models/member.ts
> +  @HasOne(() => Season, "memberId")
Why is season connected to member?

2023-10-24 12:23 UTC, MihirK1212 commented on src/db/models/onCampusOffer.ts
> +  status: string;
this could be an enum

2023-11-13 06:32 UTC, gjain-7 commented on src/db/models/recruiter.ts
yeah we did (when you went out for a little while)

2023-11-13 06:34 UTC, gjain-7 commented
Please resolve all the conflicts from the main branch. @Manas-wagh @cse210001015

2023-12-08 06:49 UTC, MihirK1212 approved these changes

2023-12-08 09:32 UTC, merged