Notifications
Web-Team-IITI-Gymkhana/tpc-backend pull request #94
Opened 2024-05-20 10:24 UTC by AryanGKulkarni

Closes #85
Closes #91 

Mails will be sent on:

- [x] Offer Table Entry
- [x] Creation of job through JAF filling
- [x] After updating job status to true
- [x] Change in eventId of ApplicationModel
- [x] Token email on login (note: I have just changed the name of function sendEmail to sendTokenEmail in auth.controller.ts)
  

Use following environment variables:

MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USER= email id of the sender
MAIL_PASSWORD= app password generated by gmail from https://security.google.com/settings/security/apppasswords
DEFAULT_MAIL_FROM= email id of the sender
APP_NAME=TPC Portal

2024-06-02 18:57 UTC, gjain-7 requested changes
Thanks! Suggestions inline.

1. Remove hardcoded strings and import from config
2. Remove console.log statements
3. Remove unnecessary comment and eslint comments

2024-06-02 18:57 UTC, gjain-7 commented on src/db/models/ApplicationModel.ts
> +          console.error(`User not found for student ${student.id}`);
```suggestion
        const student = await StudentModel.findByPk(application.studentId, {
          include: [{
          model: UserModel,
          as: "user",
        }]
        });
        if (!student) {
          throw new NotFoundException(`Student not found for offer ${application.id}`);
        }
        
        if (!student.user) {
          throw new NotFoundException(`User not found for student ${student.id}`);
```

2024-06-02 18:57 UTC, gjain-7 commented on src/db/models/ApplicationModel.ts
> +          from: { name: "TPC Portal", address: "aryangkulkarni@gmail.com" },
read for .env here

2024-06-02 18:57 UTC, gjain-7 commented on src/services/EmailService.ts
> +};
```suggestion
export class SendEmailDto = {
  from?: Address;
  recepients: Address[];
  subject: string;
  html: string;
  text?: string;
  placeholderReplacements?: Record<string, string>;
};
```

2024-06-02 18:57 UTC, gjain-7 commented on src/services/EmailService.ts
> +const nodemailer = require("nodemailer");
why `require`?

2024-06-02 18:57 UTC, gjain-7 commented on src/services/EmailService.ts
> +/* eslint-disable no-console */
```suggestion
```

2024-06-02 18:57 UTC, gjain-7 commented on src/db/models/JobModel.ts
> +    };
read from .env

put better content.

2024-06-02 18:57 UTC, gjain-7 commented on src/db/models/JobModel.ts
> +        }
use db query instead, more efficient.
you can just use `filterSalaries` which does that.
use case here https://github.com/Web-Team-IITI-Gymkhana/tpc-backend/blob/3a80c7e470c220c2bb35ad61cba93c6e342b3b5b/src/student-view/salary/salary.service.ts#L51

also include this condition
https://github.com/Web-Team-IITI-Gymkhana/tpc-backend/blob/3a80c7e470c220c2bb35ad61cba93c6e342b3b5b/src/student-view/salary/salary.service.ts#L64-L68

2024-06-02 18:57 UTC, gjain-7 commented on src/db/models/JobModel.ts
> +            from: { name: "TPC Portal", address: "aryangkulkarni@gmail.com" },
.env

2024-06-02 18:57 UTC, gjain-7 commented on src/db/models/JobModel.ts
> +          const user = await UserModel.findByPk(student.userId);
while querying include the user in student model to save these db queries.

2024-06-02 18:57 UTC, gjain-7 commented on src/db/models/OffCampusOfferModel.ts
> +      }
```suggestion
    const students = await StudentModel.findAll({
      where: {
        id: instance.map(offer => offer.studentId)
        // + include whatever needed (like user)
      }
    })
```

2024-06-02 18:57 UTC, gjain-7 commented on src/db/models/OffCampusOfferModel.ts
> +        // recepients: [{ address: "me210003016@iiti.ac.in" }],  // Put your email address for testing
same

2024-06-02 18:57 UTC, gjain-7 commented on src/db/models/OnCampusOfferModel.ts
> +        from: { name: "TPC Portal", address: "aryangkulkarni@gmail.com" },
same

2024-06-09 17:08 UTC, cse210001015 commented on src/db/models/ApplicationModel.ts
> +        });
```suggestion
        const students = await StudentModel.findAll({studentId: applications.map((application) => application.studentId)}, {
          include: [
            {
              model: UserModel,
              as: "user",
            },
          ],
        });
```

2024-06-09 17:14 UTC, gjain-7 approved these changes

2024-06-09 17:15 UTC, gjain-7 approved these changes
Just remove the N+1 queries (db query in for loop) in favour of batch queries.

2024-06-11 15:17 UTC, merged